name: Run Playwright

on: push

concurrency: serial

jobs:
  run-playwright:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@11bd71901bbe5b1630ceea73d27597364c9af683 # v4

      - name: Setup Bun
        uses: oven-sh/setup-bun@4bc047ad259df6fc24a6c9b0f9a0cb08cf17fbe5 # v2

      - name: Install Bun
        run: bun i

      - name: Install Playwright Dependencies
        run: bunx playwright install --with-deps

      - name: Run Local Playwright
        run: bunx playwright test
        env:
          AUTH0_DOMAIN: ${{ secrets.AUTH0_DOMAIN }}
          AUTH0_CLIENT_ID: ${{ secrets.AUTH0_CLIENT_ID }}
          AUTH0_CLIENT_SECRET: ${{ secrets.AUTH0_CLIENT_SECRET }}
          SESSION_SECRET: ${{ secrets.SESSION_SECRET }}
          BASE_URL: http://localhost:4173
          TEST_USER_EMAIL: ${{ secrets.TEST_USER_EMAIL }}
          TEST_USER_PASSWORD: ${{ secrets.TEST_USER_PASSWORD }}

      - name: Run Remote Playwright
        run: bunx playwright test
        env:
          AUTH0_DOMAIN:
          AUTH0_CLIENT_ID:
          AUTH0_CLIENT_SECRET:
          SESSION_SECRET:
          BASE_URL:
          HOSTING_PROVIDER: cloudflare
          TEST_USER_EMAIL: ${{ secrets.TEST_USER_EMAIL }}
          TEST_USER_PASSWORD: ${{ secrets.TEST_USER_PASSWORD }}
